### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by ghost** [mbajobue/scim-latex-tables#1]
honestly i don't understand your installation-instruction..
it would be nice to install with e.g. vundle
would you pleas explain more detailed?
thanks and kind regards

**Comment by ghost** [comment]
my fault ! i just learned to use your script in insert_mode and not to hit 'enter' but 'space'
wonderful ! thank you a lot for this!

**Comment by EdwardWong1994** [comment]
> my fault ! i just learned to use your script in insert_mode and not to hit 'enter' but 'space' wonderful ! thank you a lot for this!

Hello, i also encounter installation problem.  It will not occur the excel-like table when i input. How do you solve this?
